version: '3'
services:
  client:
    build:
      context: ./client
    networks:
      - my_network
  server:
    build:
      context: ./server
    networks:
      - my_network

networks:
  my_network:
