version: '3'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server:/app