version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
